[package]
name = "pyobs-allsky-cloudcover"
version = "1.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cloudmap_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
ball-tree = "0.5.0"
rayon = "1.10.0"
